---
plugins:
  - rubocop-minitest
  - rubocop-rake
  - rubocop-rspec

inherit_from:
  - .rubocop_todo.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 4.0

Metrics/AbcSize:
  Exclude:
    - "lib/badline/instruction.rb"
    - "lib/badline/instruction_set.rb"

Metrics/BlockLength:
  Exclude:
    - "spec/**/*.rb"

Metrics/ClassLength:
  Exclude:
    - "lib/badline/cpu.rb"
    - "lib/badline/instruction.rb"
    - "lib/badline/vic.rb"

Metrics/CyclomaticComplexity:
  Exclude:
    - "lib/badline/instruction_set.rb"

Metrics/MethodLength:
  Exclude:
    - "lib/badline/instruction.rb"
    - "lib/badline/instruction_set.rb"

Metrics/ModuleLength:
  Exclude:
    - "lib/badline/instruction_set.rb"

Metrics/PerceivedComplexity:
  Exclude:
    - "lib/badline/instruction_set.rb"

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Layout/LineLength:
  AutoCorrect: true
  Max: 120

Layout/MultilineOperationIndentation:
  EnforcedStyle: aligned
