# frozen_string_literal: true

# The emulator core: the machine, its chips, media and traps, and the
# snapshot state Computer saves and restores with, without the options,
# the rest of the snapshot code, audio or front end. lib/badline.rb and
# the Spinel harnesses in spinel/ load it, so a file the core needs is
# added here.
require "badline/version"
require "badline/integer_helper"
require "badline/region"
require "badline/timing"
require "badline/model"
require "badline/addressable"
require "badline/memory"
require "badline/color_memory"
require "badline/rom"
require "badline/ram_expansion"
require "badline/address_bus"
require "badline/instruction"
require "badline/instruction_set"
require "badline/status"
require "badline/keyboard"
require "badline/joystick"
require "badline/control_ports"
require "badline/input"
require "badline/cycleable"
require "badline/datasette"
require "badline/time_of_day"
require "badline/cia"
require "badline/via"
require "badline/sid"
require "badline/debug_register"
require "badline/reu"
require "badline/interrupts"
require "badline/traps"
require "badline/cpu"
require "badline/vic"
require "badline/keyboard_buffer"
require "badline/iec_bus"
require "badline/drive1541"
require "badline/snapshot/state"
require "badline/snapshot/setup"
require "badline/computer"
require "badline/checkpoint"
require "badline/storage"
require "badline/cartridge"
require "badline/kernal_trap"
require "badline/chrout_trap"
require "badline/media"
require "badline/machine"
