module Badline
  class Memory
    @storage: Array[Integer]
    def peek: (Integer) -> Integer
    def poke: (Integer, Integer) -> void
    def []=: (Integer, Integer) -> void
  end

  class ColorMemory
    def peek: (Integer) -> Integer
    def poke: (Integer, Integer) -> void
    def nibble: (Integer) -> Integer
  end

  class ROM
    def poke: (Integer, Integer) -> void
  end

  class AddressBus
    @port_ddr: Integer
    @port_out: Integer
    def peek: (Integer) -> Integer
    def poke: (Integer, Integer) -> void

    class OpenBus
      def peek: (Integer) -> Integer
      def poke: (Integer, Integer) -> void
    end

    class SIDSlots
      def peek: (Integer) -> Integer
      def poke: (Integer, Integer) -> void
    end
  end

  class DebugRegister
    def peek: (Integer) -> Integer
    def poke: (Integer, Integer) -> void
  end

  class VIC
    def peek: (Integer) -> Integer
    def poke: (Integer, Integer) -> void
    def phi1_data: () -> Integer

    class Bank
      def peek: (Integer) -> Integer
      def peek_phi2: (Integer) -> Integer
      def peek_color: (Integer) -> Integer
    end
  end

  class CIA
    def peek: (Integer) -> Integer
    def poke: (Integer, Integer) -> void
  end

  class SID
    def peek: (Integer) -> Integer
    def poke: (Integer, Integer) -> void
  end

  class REU
    def peek: (Integer) -> Integer
    def poke: (Integer, Integer) -> void

    class Trigger
      def peek: (Integer) -> Integer
      def poke: (Integer, Integer) -> void
    end
  end

  class Vic20
    class Bus
      @data: Integer
      @video_data: Integer
      def peek: (Integer) -> Integer
      def poke: (Integer, Integer) -> void

      class OpenBus
        def peek: (Integer) -> Integer
        def poke: (Integer, Integer) -> void
      end

      class VideoOpenBus
        def peek: (Integer) -> Integer
        def poke: (Integer, Integer) -> void
      end

      class ColorRAM
        def peek: (Integer) -> Integer
        def poke: (Integer, Integer) -> void
        def nibble: (Integer) -> Integer
      end

      class IO0
        def peek: (Integer) -> Integer
        def poke: (Integer, Integer) -> void
      end
    end

    class VIC
      @bus: Bus
      @stale: Array[bool]
      @cycles_per_line: Integer
      @lines_per_frame: Integer
      @origin_x: Integer
      @origin_y: Integer
      @columns: Integer
      @rows: Integer
      @char_shift: Integer
      @screen_base: Integer
      @char_base: Integer
      @fetch_from: Integer
      @fetch_to: Integer
      @matrix: Integer
      @row_start: Integer
      @char_line: Integer
      @text_rows: Integer
      @window_open: bool
      @window_done: bool
      def connect: (Bus) -> void
      def render=: (bool) -> void
      def peek: (Integer) -> Integer
      def poke: (Integer, Integer) -> void

      class Painter
        @render: bool
        @reverse: bool
        @written: bool
        @stale: Array[bool]
        @dirty_lines: Array[bool]
        def render=: (bool) -> void
      end
    end
  end

  class C128
    @cycles: Integer
    @pending_keys: Array[Integer]

    class Bus
      @port_ddr: Integer
      @port_out: Integer
      @address: Integer
      @data: Integer
      @port_floating: Integer
      def peek: (Integer) -> Integer
      def poke: (Integer, Integer) -> void

      class VICWrites
        def peek: (Integer) -> Integer
        def poke: (Integer, Integer) -> void
      end

      class DebugPage
        def peek: (Integer) -> Integer
        def poke: (Integer, Integer) -> void
      end
    end

    class VDC
      @selected: Integer
      @read_latch: Integer
      @write_data: Integer
      @busy_until: Integer
      @phase: Integer
      @line_units: Integer
      def peek: (Integer) -> Integer
      def poke: (Integer, Integer) -> void

      class Painter
        @width: Integer
        @height: Integer
        @line: Array[Integer]
        @dirty_lines: Array[bool]
        def paint: (Integer, Integer, Integer, bool, Integer) -> void
      end

      class Raster
        @frame: Integer
        @row: Integer
        @row_line: Integer
        @adjusting: bool
        @frame_line: Integer
        @frame_lines: Integer
        @sync_start: Integer
        @sync_lines: Integer
      end

      class Window
        @display_start: Integer
        @attribute_start: Integer
        @gap_line: bool
        @attributes_on: bool
        @screen_reverse: bool
        @underline: bool
        @blink_on: bool
        def paint: (Array[Integer], Integer, Integer, Integer) -> void
        def paint_text: (Array[Integer], Integer, Integer, Integer) -> void
        def paint_bitmap: (Array[Integer], Integer, Integer) -> void
        def each_cell: (Array[Integer]) -> void
        def paint_cell: (Array[Integer], Integer, Integer) -> void
        def colours: (Integer, Integer, bool) -> void
        def cursor_shown?: (Integer, Integer) -> bool
      end
    end
  end
end
