module Badline
  class CPU
    @operation: Symbol
    @plan: Array[Symbol]
    @a: Integer
    @x: Integer
    @y: Integer
    @stack_pointer: Integer
    @program_counter: Integer
    @address: Integer
    @pointer: Integer
    @dummy_address: Integer
    @value: Integer
    @rmw_result: Integer
    @ane_constant: Integer
    @irq: bool
    @irq_sample: bool
    @irq_pending: bool
    @boundary_irq: bool
    @pending_write: bool
    @optional_dummy: bool

    class Microcode
      attr_accessor operation: Symbol
      attr_accessor plan: Array[Symbol]
    end
  end
end

module Badline
  class Status
    @value: Integer
    @bitmask: Integer
    @low_mask: Integer
    @high_mask: Integer
  end
end
