module Badline
  module Snapshot
    class State
      @values: Array[Integer]
      @strings: Array[String]
    end

    class StateReader
      @values: Array[Integer]
      @strings: Array[String]
    end
  end
end
