#!/usr/bin/env ruby
# frozen_string_literal: true

lib = File.expand_path("../lib", __dir__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)

require "badline/options"

begin
  options = Badline::Options.parse(ARGV)
rescue Badline::Options::Error => e
  warn "badline-ruby: #{e.message}"
  warn "Try 'badline-ruby --help' for more information."
  exit 1
end

if options.help?
  puts options.help
  exit
end

jit_available = defined?(RubyVM::YJIT) && !RubyVM::YJIT.enabled?
RubyVM::YJIT.enable if options.jit? && jit_available

require "badline"

if options.headless?
  begin
    Badline::Audio::CLI.new(options).run
  rescue Badline::Audio::CLI::Error => e
    warn "badline-ruby: #{e.message}"
    exit 1
  rescue Interrupt
    exit 130
  end
  exit
end

begin
  require "badline/gui"
rescue Badline::SDL::Error => e
  warn "badline-ruby: can't open the window: #{e.message}. " \
       "Install SDL2 with 'brew install sdl2' or 'apt install libsdl2-2.0-0'."
  exit 1
end

begin
  application = Badline::GUI::Application.new(media_path: options.media_path, autostart: options.autostart?,
                                              song: options.song, sid_model: options.sid_model,
                                              sound: options.sound?)
rescue Badline::Storage::SIDFile::FormatError, Badline::Storage::T64::FormatError,
       Badline::Storage::TAP::FormatError, Badline::Storage::CRTFile::FormatError,
       Badline::Cartridge::UnsupportedTypeError => e
  warn "badline-ruby: #{options.media_path}: #{e.message}"
  exit 1
end

application.run
