#!/usr/bin/env ruby
# frozen_string_literal: true

lib = File.expand_path("../lib", __dir__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)

require "badline/options"

$stdout.sync = true

begin
  options = Badline::Options.parse(ARGV)
rescue Badline::Options::Error => e
  warn "badline-ruby: #{e.message}"
  warn "Try 'badline-ruby --help' for more information."
  exit 1
end

if options.help?
  puts options.help
  exit
end

jit_available = defined?(RubyVM::YJIT) && !RubyVM::YJIT.enabled?
RubyVM::YJIT.enable if options.jit? && jit_available

require "badline"

# Quiets IO::Buffer's experimental warning.
Warning[:experimental] = false

def load_sdl
  require "badline/ffi"
  require "badline/frontend"
end

if options.headless?
  require "badline/audio/console"
  console = if options.player_window?
              lambda do |input:, output:|
                load_sdl
                Badline::Frontend::PlayerController.new(input:, output:)
              end
            else
              Badline::Audio::Console.method(:new)
            end
  sink = lambda do |rate:, exact_rate:|
    load_sdl
    Badline::Frontend::AudioSink.new(rate:, exact_rate:)
  rescue Badline::FFI::Error => e
    raise Badline::Audio::Playback::DeviceError, e.message
  end
  exit Badline::Audio::CLI.run(options, sink:, console:)
end

begin
  load_sdl
rescue Badline::FFI::Error => e
  warn "badline-ruby: can't open the window: #{e.message}. " \
       "Install SDL2 with 'brew install sdl2' or 'apt install libsdl2-2.0-0'."
  exit 1
end

begin
  exit Badline::Frontend.run(options)
rescue Interrupt
  exit 130
end
