# frozen_string_literal: true

# The native badline: the emulator core compiled with Spinel, playing in an
# SDL2 window. It requires the core file by file rather than through
# lib/badline.rb, which also loads the CRuby-only front end.
require "badline/version"
require "badline/integer_helper"
require "badline/addressable"
require "badline/memory"
require "badline/color_memory"
require "badline/rom"
require "badline/address_bus"
require "badline/instruction"
require "badline/instruction_set"
require "badline/status"
require "badline/keyboard"
require "badline/joystick"
require "badline/control_ports"
require "badline/input"
require "badline/cycleable"
require "badline/datasette"
require "badline/time_of_day"
require "badline/cia"
require "badline/sid"
require "badline/debug_register"
require "badline/interrupts"
require "badline/traps"
require "badline/cpu"
require "badline/vic"
require "badline/keyboard_buffer"
require "badline/computer"
require "badline/storage"
require "badline/cartridge"
require "badline/kernal_trap"
require "badline/chrout_trap"
require "badline/media"

require "badline/native/build_info"
require "badline/native/version"
require "badline/native/options"
require "badline/native/sdl"
require "badline/native/frame_rate"
require "badline/native/screen"
require "badline/native/sound"
require "badline/native/pacer"
require "badline/native/keys"
require "badline/native/controls"
require "badline/native/app"
